config/routes.rb
Rails.application.routes.draw do

  root to: 'books#index'

  resources :books do 
    resources :articles do
      resources :sections do
        resources :comments
      end
    end          
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :book
  has_many :sections
end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :articles
  has_many :sections, through: :articles
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :section
end

app/models/section.rb
class Section < ActiveRecord::Base
  belongs_to :article
  belongs_to :book
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :set_book

  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = @book.articles.build(article_params)

    if @article.save
      redirect_to book_articles_url, notice: 'Article was successfully created.' 
    else
      render :new
    end
  end

  def update
    if @article.update(article_params)
      redirect_to book_articles_url, notice: 'Article was successfully updated.' 
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
    redirect_to book_articles_url, notice: 'Article was successfully destroyed.'
  end

  private

    def set_book
      @book = Book.find(params[:book_id])
    end
    
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :description, :book_id)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  def index
    @books = Book.all
  end

  def show
  end

  def new
    @book = Book.new
  end

  def edit
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to books_url, notice: 'Book was successfully created.' 
    else
      render :new
    end
  end

  def update
    if @book.update(book_params)
      redirect_to books_url, notice: 'Book was successfully updated.' 
    else
      render :edit
    end
  end

  def destroy
    @book.destroy
    redirect_to books_url, notice: 'Book was successfully destroyed.' 
  end

  private
    
    def set_book
      @book = Book.find(params[:id])
    end

    def book_params
      params.require(:book).permit(:title, :description)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :set_section
  before_action :set_article
  before_action :set_book

  def index
    @comments = Comment.all
  end

  def show
  end

  def new
    @comment = Comment.new
  end

  def edit
  end

  def create
    @comment = @section.comments.create(comment_params)
    
    if @comment.save
      redirect_to book_article_section_path(@book,@article,@section), notice: 'Comment was successfully created.'
    else
      render :new
    end
  end

  def update
    if @comment.update(comment_params)
      redirect_to book_article_section_path(@book,@article,@section), notice: 'Comment was successfully updated.' 
    else
      render :edit
    end
  end

  def destroy
    @comment.destroy
    redirect_to book_article_section_path(@book,@article,@section), notice: 'Comment was successfully destroyed.'
  end

  private
    
    def set_book
      @book = Book.find(params[:book_id])
    end
    
    def set_article
      @article = Article.find(params[:article_id])
    end

    def set_section
      @section = Section.find(params[:section_id])
    end

    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:body, :section_id)
    end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: [:show, :edit, :update, :destroy]
  before_action :set_article
  before_action :set_book

  def index
    @sections = Section.all
  end

  def show
  end

  def new
    @section = Section.new
  end

  def edit
  end

  def create
    @section = @article.sections.build(section_params)
    if @section.save
      redirect_to book_article_sections_url, notice: 'Section was successfully created.'
    else
      render :new 
    end
  end

  def update
    if @section.update(section_params)
      redirect_to book_article_sections_url, notice: 'Section was successfully updated.'
    else
      render :edit 
    end
  end

  def destroy
    @section.destroy
    redirect_to book_article_sections_url, notice: 'Section was successfully destroyed.'
  end

  private

    def set_book
      @book = Book.find(params[:book_id])
    end
    
    def set_article
      @article = Article.find(params[:article_id])
    end

    def set_section
      @section = Section.find(params[:id])
    end

    def section_params
      params.require(:section).permit(:title, :description, :article_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/articles/_form.html.erb
<%= form_for([@book,@article], html: { multipart: true, class: "form-horizontal" } ) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', book_articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each_with_index do |article, index| %>
    <% @book = article.book %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.description %></td>
      <td><%= link_to 'Show', book_article_path(@book,article) %></td>
      <td><%= link_to 'Edit', edit_book_article_path(@book,article) %></td>
      <td><%= link_to 'Destroy', book_article_path(@book,article), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_book_article_path %>
<%= link_to 'Back', books_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', book_articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @article.description %>
</p>

<%= link_to 'Edit', edit_book_article_path(@book,@article) %> |
<%= link_to 'Back', book_articles_path %><br>

<% @article.sections.each_with_index do |section, index| %>
	<%= link_to section.title, book_article_section_path(@book,@article,section) %>
<% end%><br>

<%= link_to 'New Section', new_book_article_section_path(@book,@article,@section) %>

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.description %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @book.description %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %><br>

<% @book.articles.each_with_index do |article, index| %>
	<%= link_to article.title, book_article_path(@book, article) %>
<% end%><br>

<%= link_to 'New Article', new_book_article_path(@book,@article) %>

app/views/comments/_form.html.erb
<%= form_for([@book,@article,@section, @section.comments.build]) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', book_article_section_comment_path(@book,@article,@section,@comment) %> |
<%= link_to 'Back', book_article_section_comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Comments</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each_with_index do |comment, index| %>
    <% @section = comment.section %>
    <% @article = @section.article %>
    <% @book = @article.book %>
      <tr>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', book_article_section_comment_path(@book,@article,@section,comment) %></td>
        <td><%= link_to 'Edit', edit_book_article_section_comment_path(@book,@article,@section,comment) %></td>
        <td><%= link_to 'Destroy', book_article_section_comment_path(@book,@article,@section,comment), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_book_article_section_comment_path %>
<%= link_to 'Back', book_article_sections_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', book_article_section_comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_book_article_section_comment_path(@book,@article,@section,@comment) %> |
<%= link_to 'Back', book_article_section_comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BookApplication</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sections/_form.html.erb
<%= form_for([@book,@article,@section], html: { multipart: true, class: "form-horizontal" } ) do |f| %>
  <% if @section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
      <% @section.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sections/edit.html.erb
<h1>Editing Section</h1>

<%= render 'form' %>

<%= link_to 'Show', @section %> |
<%= link_to 'Back', book_article_sections_path %>

app/views/sections/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Sections</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sections.each_with_index do |section, index| %>
    <% @article = section.article %>
    <% @book = @article.book %>
      <tr>
        <td><%= section.title %></td>
        <td><%= section.description %></td>
        <td><%= link_to 'Show', book_article_section_path(@book,@article,section) %></td>
        <td><%= link_to 'Edit', edit_book_article_section_path(@book,@article,section) %></td>
        <td><%= link_to 'Destroy', book_article_section_path(@book,@article,section), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Section', new_book_article_section_path %>
<%= link_to 'Back', book_articles_path %>

app/views/sections/new.html.erb
<h1>New Section</h1>

<%= render 'form' %>

<%= link_to 'Back', book_article_sections_path %>

app/views/sections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @section.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @section.description %>
</p>

<h2>Comments</h2>
<% @section.comments.each do |comment| %>
  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>
<% end %>

<h2>Add a comment:</h2>
<%= form_for([@book,@article,@section, @section.comments.build]) do |f| %>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Edit', edit_book_article_section_path(@book, @article, @section) %> |
<%= link_to 'Back', book_article_sections_path %><br>